server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:nt-ms.jks
    key-store-password: secret
    client-auth: need
    trust-store: classpath:nt-ms.jks
    trust-store-password: secret